### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/iris-rad-studio-samples#3]
#11 102.0
#11 102.0 [iris-rad-studio-samples]     Compile FAILURE
#11 102.0 ERROR! Class 'Form.Test.Person', used by '**User.forms.TestForm:property:children', does not exist**
#11 ERROR: process "/bin/sh -c iris start IRIS \t&& iris session IRIS < iris.script     && iris stop IRIS quietly"
 did not complete successfully: exit code: 1
------
 > [7/7] RUN iris start IRIS    && iris session IRIS < iris.script     && iris stop IRIS quietly:
#11 102.0 ERROR! Class 'Form.Test.Person', used by 'User.forms.TestForm:property:children', does not exist

**Comment by jrpereirajr** [comment]
Thanks for letting me know this issue.
I have to copy a package from a ZPM dependency which is no longer public in its module.xml.
Image now could be built.

**Comment by rcemper** [comment]
thanks for the quick fix
